spring:
  datasource:
    url: jdbc:postgresql://auth_db:5432/auth_db
    username: postgres
    password: postgres

student:
  service:
    url: http://student_service:8082

logging:
  level:
    com.universite.auth: INFO
    org.springframework.security: INFO

app:
  sample-data:
    enabled: ${ENABLE_SAMPLE_DATA:true}
